/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VJ4fLngJ0k2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"

export default function signup() {
  return (
    <div className="w-full space-y-12">
      <div className="mx-auto max-w-2xl space-y-6">
        <div className="space-y-2 text-center">
          <h1 className="text-4xl font-bold">Create an account</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter your information to create an account</p>
        </div>
        <div className="border border-gray-200 rounded-lg shadow-sm dark:border-gray-800">
          <div className="p-8">
            <div className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="email">Email</Label>
                <Input id="email" placeholder="m@example.com" required type="email" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="username">Username</Label>
                <Input id="username" required />
              </div>
              <div className="space-y-2">
                <Label htmlFor="password">Password</Label>
                <Input id="password" required type="password" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="confirm-password">Confirm Password</Label>
                <Input id="confirm-password" required type="password" />
              </div>
            </div>
          </div>
          <div className="p-8 bg-gray-100 dark:bg-gray-800">
            <div className="space-y-2">
              <p className="text-sm text-gray-500 dark:text-gray-400">
                By clicking the button below, you agree to our
                <Link className="underline" href="#">
                  Terms of Service
                </Link>
                and
                <Link className="underline" href="#">
                  Privacy Policy
                </Link>
                .
              </p>
              <Button className="w-full">Review and Create Account</Button>
            </div>
          </div>
        </div>
        <Separator className="my-12" />
        <div className="text-center space-y-2">
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Already have an account?
            <Link className="underline" href="/signin">
              Sign in
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
