/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/AcSsEFVEZbt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function signin() {
  return (
    <div className="mx-auto max-w-[350px] space-y-6">
      <div className="space-y-2 text-center">
        <h1 className="text-3xl font-bold">Sign In</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter your information to sign in</p>
      </div>
      <div className="space-y-2">
        <Label htmlFor="email">Email</Label>
        <Input id="email" placeholder="m@example.com" type="email" />
      </div>
      <div className="space-y-2">
        <div className="flex items-center">
          <Label className="flex-1" htmlFor="password">
            Password
          </Label>
          <Link className="text-sm underline" href="#">
            Forgot password?
          </Link>
        </div>
        <Input id="password" type="password" />
      </div>
      <Button className="w-full">Sign In</Button>
      <div className="mt-4 text-center text-sm">
        Don't have an account?
        <Link className="underline" href="/signup">
          Sign up
        </Link>
      </div>
    </div>
  )
}
